---
- name: Build VM
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    vm_state: present

  tasks:
    - name: Build VM
      ansible.builtin.include_role:
        name: virtual_machine
