---
- name: Decommission VM
  hosts: "{{ vm_name }}.zach.lab"
  connection: local
  gather_facts: no

  vars:
    vm_state: absent

  tasks:
    - name: Decommission VM
      ansible.builtin.import_role:
        name: virtual_machine
      delegate_to: localhost
